# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

     place.manager:
         class: Zombies\GameBundle\Utils\PlaceService


     coordinates.manager:
         class: Zombies\GameBundle\Utils\CoordinatesService

     resources.manager:
         class: Zombies\GameBundle\Utils\ResourcesService

     inhabitants.manager:
         class: Zombies\GameBundle\Utils\InhabitantsService
